services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskora-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
    networks:
      - taskora-api-network
    command: sh -c "sleep 10 && npx prisma db push --schema=src/database/prisma/schema.prisma && npm start"

  mysql:
    image: mysql:8.0
    container_name: taskora-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - taskora-api-network

  redis:
    image: redis:alpine
    container_name: taskora-redis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - taskora-api-network

networks:
  taskora-api-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
