name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Lint, and Validate
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Use Node.js 20
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # 3️⃣ Install dependencies
      - run: npm ci

      # 4️⃣ Validate Prisma schema
      - run: npm run db:validate

      # 5️⃣ Generate Prisma client
      - run: npm run db:generate

      # 6️⃣ Check formatting
      - run: npm run format:check

      # 7️⃣ Lint check
      - run: npm run lint:check

      # 8️⃣ Build project
      - run: npm run build
