name: Node.js CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - '.dockerignore'
      - 'LICENSE'
      - '.vscode/**'
      - 'swagger.json'

jobs:
  build:
    name: Build, Lint, and Validate
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Use Node.js 20
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # 3️⃣ Install dependencies
      - run: npm ci

      # 4️⃣ Generate Prisma client
      - run: npm run db:generate

      # 5️⃣ Check formatting
      - run: npm run format:check

      # 6️⃣ Lint check
      - run: npm run lint:check

      # 7️⃣ Build project
      - run: npm run build
